In [1]:
from Mura import *

In [2]:
acc = {}
kappa = {}

In [3]:
for study_type in ['XR_SHOULDER','XR_FINGER','XR_FOREARM','XR_HAND','XR_HUMERUS','XR_ELBOW','XR_WRIST']:

    print(study_type, ": \n")
    study_data = get_study_level_data(study_type)
    dataloaders = get_dataloaders(study_data, batch_size=16)
    dataset_sizes = {x: len(study_data[x]) for x in data_cat}

    model = models.densenet121(pretrained=True)
    model.classifier = nn.Linear(in_features=1024, out_features=2, bias=False)
    model = model.cuda()

    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=1,verbose=True)

    model, acc[study_type], kappa[study_type] = train_model(model, criterion, optimizer, dataloaders, scheduler, dataset_sizes, num_epochs=10)
    print('-' * 10)
    print()
    torch.cuda.empty_cache()

  0%|          | 96/36804 [00:00<00:38, 958.47it/s]

XR_SHOULDER : 



100%|██████████| 3197/3197 [00:00<00:00, 5339.10it/s] 


Train batches: 524
Valid batches: 36 

Epoch 1/10
----------

train Loss: 0.0357 Acc: 0.7096
Confusion Meter:
 [[3079 1132]
 [1301 2867]]
kappa:  0.419126894691074


valid Loss: 0.0335 Acc: 0.7655
Confusion Meter:
 [[246  39]
 [ 93 185]]
kappa:  0.5298895509925229

Time elapsed: 2m 2s

Epoch 2/10
----------

train Loss: 0.0312 Acc: 0.7667
Confusion Meter:
 [[3358  853]
 [1102 3066]]
kappa:  0.53320253119576


valid Loss: 0.0320 Acc: 0.7638
Confusion Meter:
 [[219  66]
 [ 67 211]]
kappa:  0.5274371580216214

Time elapsed: 4m 5s

Epoch 3/10
----------

train Loss: 0.0297 Acc: 0.7815
Confusion Meter:
 [[3384  827]
 [1004 3164]]
kappa:  0.5628487131533482


valid Loss: 0.0336 Acc: 0.7691
Confusion Meter:
 [[257  28]
 [102 176]]
kappa:  0.536602043788226

Time elapsed: 6m 7s

Epoch 4/10
----------

train Loss: 0.0277 Acc: 0.8018
Confusion Meter:
 [[3473  738]
 [ 923 3245]]
kappa:  0.6034323294630984


valid Loss: 0.0330 Acc: 0.7780
Confusion Meter:
 [[255  30]
 [ 95 183]]
kappa:  0.55460270

 26%|██▋       | 9744/36804 [00:00<00:00, 96956.50it/s]

----------

XR_FINGER : 



100%|██████████| 3197/3197 [00:00<00:00, 6637.25it/s] 

Train batches: 320
Valid batches: 29 

Epoch 1/10
----------



train Loss: 0.0335 Acc: 0.7299
Confusion Meter:
 [[2601  537]
 [ 842 1126]]
kappa:  0.41295753539300856


valid Loss: 0.0371 Acc: 0.7267
Confusion Meter:
 [[197  17]
 [109 138]]
kappa:  0.46588568486096804

Time elapsed: 1m 15s

Epoch 2/10
----------

train Loss: 0.0285 Acc: 0.7869
Confusion Meter:
 [[2717  421]
 [ 667 1301]]
kappa:  0.5394870478742717


valid Loss: 0.0427 Acc: 0.6790
Confusion Meter:
 [[212   2]
 [146 101]]
kappa:  0.38237317594235437

Time elapsed: 2m 31s

Epoch 3/10
----------

train Loss: 0.0256 Acc: 0.8239
Confusion Meter:
 [[2799  339]
 [ 560 1408]]
kappa:  0.6204046475372785


valid Loss: 0.0347 Acc: 0.7679
Confusion Meter:
 [[164  50]
 [ 57 190]]
kappa:  0.5344181524724626

Time elapsed: 3m 46s

Epoch 4/10
----------

train Loss: 0.0236 Acc: 0.8378
Confusion Meter:
 [[2851  287]
 [ 541 1427]]
kappa:  0.6492639614374927


valid Loss: 0.0338 Acc: 0.7766
Confusion Meter:
 [[183  31]
 [ 72 175]]
kappa:  0.5565196275299105

Time elapsed: 5m 1s

Epoch 5/10
---------

 80%|████████  | 29521/36804 [00:00<00:00, 294761.21it/s]

----------

XR_FOREARM : 



100%|██████████| 3197/3197 [00:00<00:00, 10041.37it/s]

Train batches: 115
Valid batches: 19 

Epoch 1/10
----------



train Loss: 0.0335 Acc: 0.7600
Confusion Meter:
 [[1025  139]
 [ 299  362]]
kappa:  0.45187228113291383


valid Loss: 0.0377 Acc: 0.7209
Confusion Meter:
 [[145   5]
 [ 79  72]]
kappa:  0.44276457883369313

Time elapsed: 0m 28s

Epoch 2/10
----------

train Loss: 0.0255 Acc: 0.8345
Confusion Meter:
 [[1064  100]
 [ 202  459]]
kappa:  0.629479489775476


valid Loss: 0.0370 Acc: 0.7508
Confusion Meter:
 [[146   4]
 [ 71  80]]
kappa:  0.5023916062336059

Time elapsed: 0m 56s

Epoch 3/10
----------

train Loss: 0.0223 Acc: 0.8586
Confusion Meter:
 [[1091   73]
 [ 185  476]]
kappa:  0.6823886049787113


valid Loss: 0.0293 Acc: 0.8140
Confusion Meter:
 [[147   3]
 [ 53  98]]
kappa:  0.6283131201764058

Time elapsed: 1m 24s

Epoch 4/10
----------

train Loss: 0.0192 Acc: 0.8811
Confusion Meter:
 [[1099   65]
 [ 152  509]]
kappa:  0.7351086621357055


valid Loss: 0.0385 Acc: 0.7841
Confusion Meter:
 [[146   4]
 [ 61  90]]
kappa:  0.5686443106907425

Time elapsed: 1m 52s

Epoch 5/10
----------

 85%|████████▌ | 31345/36804 [00:00<00:00, 310313.35it/s]

----------

XR_HAND : 



100%|██████████| 3197/3197 [00:00<00:00, 6507.60it/s] 


Train batches: 347
Valid batches: 29 

Epoch 1/10
----------

train Loss: 0.0333 Acc: 0.7568
Confusion Meter:
 [[3822  237]
 [1111  373]]
kappa:  0.23728712174740513


valid Loss: 0.0374 Acc: 0.6957
Confusion Meter:
 [[223  48]
 [ 92  97]]
kappa:  0.3483759991905291

Time elapsed: 1m 21s

Epoch 2/10
----------

train Loss: 0.0294 Acc: 0.7972
Confusion Meter:
 [[3812  247]
 [ 877  607]]
kappa:  0.4023583237840461


valid Loss: 0.0383 Acc: 0.7457
Confusion Meter:
 [[254  17]
 [100  89]]
kappa:  0.4372176677262842

Time elapsed: 2m 43s

Epoch 3/10
----------

train Loss: 0.0273 Acc: 0.8171
Confusion Meter:
 [[3814  245]
 [ 769  715]]
kappa:  0.4746026570666975


valid Loss: 0.0363 Acc: 0.7457
Confusion Meter:
 [[251  20]
 [ 97  92]]
kappa:  0.4400982064832924

Time elapsed: 4m 5s

Epoch 4/10
----------

train Loss: 0.0257 Acc: 0.8320
Confusion Meter:
 [[3841  218]
 [ 713  771]]
kappa:  0.5209524968561113


valid Loss: 0.0340 Acc: 0.7522
Confusion Meter:
 [[249  22]
 [ 92  97]]
kappa:  0.4

 23%|██▎       | 8473/36804 [00:00<00:00, 83318.69it/s]

----------

XR_HUMERUS : 



100%|██████████| 3197/3197 [00:00<00:00, 10418.92it/s]


Train batches: 80
Valid batches: 18 

Epoch 1/10
----------

train Loss: 0.0330 Acc: 0.7398
Confusion Meter:
 [[538 135]
 [196 403]]
kappa:  0.474852196472672


valid Loss: 0.0238 Acc: 0.8542
Confusion Meter:
 [[129  19]
 [ 23 117]]
kappa:  0.7078825347758887

Time elapsed: 0m 20s

Epoch 2/10
----------

train Loss: 0.0252 Acc: 0.8192
Confusion Meter:
 [[561 112]
 [118 481]]
kappa:  0.6369367468758144


valid Loss: 0.0251 Acc: 0.8299
Confusion Meter:
 [[119  29]
 [ 20 120]]
kappa:  0.6600501059934478

Time elapsed: 0m 40s

Epoch 3/10
----------

train Loss: 0.0209 Acc: 0.8774
Confusion Meter:
 [[595  78]
 [ 78 521]]
kappa:  0.7538840117382364


valid Loss: 0.0267 Acc: 0.8299
Confusion Meter:
 [[121  27]
 [ 22 118]]
kappa:  0.659787849566056

Epoch     2: reducing learning rate of group 0 to 1.0000e-05.
Time elapsed: 0m 60s

Epoch 4/10
----------

train Loss: 0.0162 Acc: 0.9049
Confusion Meter:
 [[633  40]
 [ 81 518]]
kappa:  0.8083812654067379


valid Loss: 0.0249 Acc: 0.8403
Confusion

 40%|████      | 14849/36804 [00:00<00:00, 148307.69it/s]

----------

XR_ELBOW : 



100%|██████████| 3197/3197 [00:00<00:00, 6681.90it/s] 

Train batches: 309
Valid batches: 30 

Epoch 1/10
----------



train Loss: 0.0314 Acc: 0.7625
Confusion Meter:
 [[2541  384]
 [ 787 1219]]
kappa:  0.49191979088308474


valid Loss: 0.0269 Acc: 0.8258
Confusion Meter:
 [[224  11]
 [ 70 160]]
kappa:  0.6506191735077222

Time elapsed: 1m 13s

Epoch 2/10
----------

train Loss: 0.0265 Acc: 0.8217
Confusion Meter:
 [[2639  286]
 [ 593 1413]]
kappa:  0.6215523016874143


valid Loss: 0.0250 Acc: 0.8258
Confusion Meter:
 [[212  23]
 [ 58 172]]
kappa:  0.6510076441973593

Time elapsed: 2m 26s

Epoch 3/10
----------

train Loss: 0.0247 Acc: 0.8343
Confusion Meter:
 [[2671  254]
 [ 563 1443]]
kappa:  0.6481895365950378


valid Loss: 0.0277 Acc: 0.8301
Confusion Meter:
 [[222  13]
 [ 66 164]]
kappa:  0.6593406593406593

Time elapsed: 3m 39s

Epoch 4/10
----------

train Loss: 0.0226 Acc: 0.8505
Confusion Meter:
 [[2689  236]
 [ 501 1505]]
kappa:  0.6837552587484821


valid Loss: 0.0274 Acc: 0.8473
Confusion Meter:
 [[223  12]
 [ 59 171]]
kappa:  0.6939229592546238

Epoch     3: reducing learning rate of grou

 54%|█████▎    | 19778/36804 [00:00<00:00, 196129.06it/s]

----------

XR_WRIST : 



100%|██████████| 3197/3197 [00:00<00:00, 4518.29it/s]


Train batches: 610
Valid batches: 42 

Epoch 1/10
----------

train Loss: 0.0285 Acc: 0.7948
Confusion Meter:
 [[5049  712]
 [1288 2699]]
kappa:  0.5659490889628485


valid Loss: 0.0283 Acc: 0.8088
Confusion Meter:
 [[318  46]
 [ 80 215]]
kappa:  0.6090935625712053

Time elapsed: 2m 23s

Epoch 2/10
----------

train Loss: 0.0244 Acc: 0.8364
Confusion Meter:
 [[5275  486]
 [1109 2878]]
kappa:  0.653200637066276


valid Loss: 0.0269 Acc: 0.8164
Confusion Meter:
 [[326  38]
 [ 83 212]]
kappa:  0.6232595497389619

Time elapsed: 4m 46s

Epoch 3/10
----------

train Loss: 0.0229 Acc: 0.8519
Confusion Meter:
 [[5315  446]
 [ 998 2989]]
kappa:  0.6869120166153287


valid Loss: 0.0247 Acc: 0.8498
Confusion Meter:
 [[342  22]
 [ 77 218]]
kappa:  0.6907496504159456

Time elapsed: 7m 8s

Epoch 4/10
----------

train Loss: 0.0214 Acc: 0.8599
Confusion Meter:
 [[5331  430]
 [ 936 3051]]
kappa:  0.7043605798061614


valid Loss: 0.0255 Acc: 0.8452
Confusion Meter:
 [[331  33]
 [ 69 226]]
kappa:  0.683

In [4]:
f = open("result.txt",'w')
for item in acc:
    print()
    f.write(item + "accuracy: " + str(acc[item]) + "\n")
    f.write(item + "kappa: " + str(kappa[item]) + "\n")
f.close()